package top

// WorkflowID identifies one fixed, allowlisted Solis workflow that the
// interactive console may run in its bounded workflow-output panel. It is
// deliberately not an arbitrary command or shell fragment.
type WorkflowID string

const (
	WorkflowInvestigate WorkflowID = "investigate"
	WorkflowBundle      WorkflowID = "bundle"
	WorkflowWatch       WorkflowID = "watch"
	WorkflowObserve     WorkflowID = "observe"
	WorkflowDoctor      WorkflowID = "doctor"
	WorkflowEBPFDoctor  WorkflowID = "ebpf_doctor"
	WorkflowInventory   WorkflowID = "inventory"
	WorkflowStatus      WorkflowID = "status"
	WorkflowVersion     WorkflowID = "version"
)

// LaunchRequest contains only a fixed workflow identity and the currently
// selected inventory VM. The CLI validates and expands it without a shell.
type LaunchRequest struct {
	Workflow WorkflowID
	VM       string
}

// WorkflowResult is the bounded application-facing result of one allowlisted
// workflow. Detail is deliberately separate so a large structured artifact is
// never dumped into the terminal by default.
type WorkflowResult struct {
	Output string
	Detail *WorkflowDetail
}

// WorkflowDetail is one private structured artifact held in memory until an
// operator explicitly requests persistence. SuggestedName is generated by the
// trusted CLI workflow, never supplied by terminal input.
type WorkflowDetail struct {
	SuggestedName string
	Contents      []byte
}

type applicationWorkflow struct {
	ID          WorkflowID
	Label       string
	Description string
	RequiresVM  bool
}

var applicationWorkflows = []applicationWorkflow{
	{ID: WorkflowInvestigate, Label: "Investigate selected VM", Description: "run conservative noisy-neighbor diagnosis with eBPF evidence", RequiresVM: true},
	{ID: WorkflowBundle, Label: "Capture evidence bundle", Description: "write a private checksummed incident bundle for the selected VM", RequiresVM: true},
	{ID: WorkflowWatch, Label: "Watch selected VM", Description: "run a bounded noisy-neighbor watch with suspect discovery", RequiresVM: true},
	{ID: WorkflowObserve, Label: "Observe selected VM", Description: "summarize one unified snapshot; optionally save its detailed JSON", RequiresVM: true},
	{ID: WorkflowDoctor, Label: "System doctor", Description: "check configuration, inventory, libvirt, and host prerequisites"},
	{ID: WorkflowEBPFDoctor, Label: "eBPF doctor", Description: "inspect BTF, capabilities, lockdown, hooks, and object readiness"},
	{ID: WorkflowInventory, Label: "VM inventory", Description: "print the resolved local libvirt VM inventory"},
	{ID: WorkflowStatus, Label: "Current status", Description: "collect one non-interactive VM and storage pressure report"},
	{ID: WorkflowVersion, Label: "Version and build", Description: "show version, commit, build time, Go version, and platform"},
}

// workflowCount returns the number of fixed workflows exposed by the command center.
func workflowCount() int {
	return len(applicationWorkflows)
}

// normalizedWorkflowIndex wraps keyboard navigation around the fixed workflow list.
func normalizedWorkflowIndex(index int) int {
	if len(applicationWorkflows) == 0 {
		return 0
	}
	index %= len(applicationWorkflows)
	if index < 0 {
		index += len(applicationWorkflows)
	}
	return index
}

// selectedWorkflowRequest creates a launch request only when the selected workflow's VM requirement is met.
func selectedWorkflowRequest(index int, selectedVM string) (LaunchRequest, bool) {
	if len(applicationWorkflows) == 0 {
		return LaunchRequest{}, false
	}
	workflow := applicationWorkflows[normalizedWorkflowIndex(index)]
	if workflow.RequiresVM && selectedVM == "" {
		return LaunchRequest{}, false
	}
	return LaunchRequest{Workflow: workflow.ID, VM: selectedVM}, true
}
